### ISSUE TITLE
分布式启动home服务时报net.bindException

### ISSUE THREAD

**Issue by hariC7777** [zfoo-project/tank-game-server#6]
![图片](https://user-images.githubusercontent.com/54092931/173348246-d72814ae-9ccf-4f28-b5bc-f433bc8dc6f6.png)

**Comment by jaysunxiao** [comment]
检查自己的端口占用情况

**Comment by hariC7777** [comment]
测试下来 home服务和cache服务不能同时启动 后启动的报错 是哪里设置不对吗

**Comment by hariC7777** [comment]
[INFO ] [main] com.zfoo.net.core.AbstractServer.doStart(AbstractServer.java:100) - TcpServer started at [192.168.31.6:12400]  两个服务使用同一个端口启动了tcpserver

**Comment by hariC7777** [comment]
<img width="713" alt="截屏2022-06-15 19 49 47" src="https://user-images.githubusercontent.com/54092931/173820457-7da3085b-880b-49b0-8aca-489d2cb0e6b2.png">

相似问题在启动多个provider也会碰到
解决方法：检测端口时增加ip地址限定，避免serversocker构造器选择其他本机地址

**Comment by jaysunxiao** [comment]
已经修复
https://github.com/zfoo-project/zfoo/commit/b2b6f6b33cdd004a17038558cc20772b93c450ad
